site_name: RWA Documentation
site_url: https://rnd-hsm-klassik.github.io/rwa-doc/
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.blocks.caption

# nav:
#   - Home: index.md
#   - First File: first_file.md

repo_url: https://github.com/rnd-hsm-klassik/rwa-doc
repo_name: rwa-doc
