site_name: RWA Documentation
site_url: https://rnd-hsm-klassik.github.io/rwa-doc/
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js

nav:
  - Home: index.md
  - RWA Creator:
    - rwa-creator/index.md
    - Getting Started: rwa-creator/getting-started.md
    - General Game Structure: rwa-creator/overview.md
    - Map View: rwa-creator/map-view.md
    - Game View: rwa-creator/game-view.md
    - State View: rwa-creator/state-view.md
    - Scene View: rwa-creator/scene-view.md
    # - History View: rwa-creator/history-view.md
    # - Log View: rwa-creator/log-view.md

repo_url: https://github.com/rnd-hsm-klassik/rwa-doc
repo_name: rwa-doc
